############## Production properties #############################################################
# This is the default property file which can be used as a template for default configuration.   #
# Copy this file to `/config/application.properties`, with the runnable jar in the `/` directory #
##################################################################################################

spring:
  datasource:
    # DATABASE PROPERTIES
    driverClassName: org.postgresql.Driver
    # Change <MyDb> with the name of your database name
    url: jdbc:postgresql://localhost:5432/events

    # Username to log in to the database
    # It's recommended to create a dedicated Database user instead of using the default postgres user
    username: postgres

    # Password to log in with <MyDbPassword> in database <MyDb>
    password: 

  data.jpa.repositories.enabled: true

  jpa:
    # Set to false in production to prevent spamming of console
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop

    # This setting defines the database creation/update behaviour. Change with caution.
    properties.hibernate.default_schema: public

  # Spring mail
  mail:
    host: 127.0.0.1
    port: 1025

  # Thymeleaf
  thymeleaf:
    mode: HTML5
    encoding: UTF-8

# Database migration automation. Set to false for development
flyway.enabled: false
# spring.jpa.properties.hibernate.hbm2ddl.auto: none

# Serve connect
server:
    port: 8080
    context-path: /events

# CH Connect Configuration
wisvch.connect:
  issuerUri: https://connect.ch.tudelft.nl
  clientUri: http://localhost:8080/events

  # Change <MyLDAPgroup> to a LDAP group you're in (e.g. hoothub, dienst2, etc.)
  admin-groups: diest2, chbeheer
  beta-users: svenp,ruthk

# CH Payments Configuration
wisvch.payments:
    issuerUri: https://ch.tudelft.nl/payments
    clientUri: http://localhost:8080/events